//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetStreamer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweet
    {
        public long id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int retweet_count { get; set; }
        public int favorite_count { get; set; }
        public string user_name { get; set; }
        public long user_id { get; set; }
        public string text { get; set; }
        public string source { get; set; }
    }
}
