//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentiment.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class source
    {
        public source()
        {
            this.tweets = new HashSet<tweet>();
        }
    
        public long id { get; set; }
        public string source1 { get; set; }
    
        public virtual ICollection<tweet> tweets { get; set; }
    }
}
