//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentiment.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class tweet
    {
        public long id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int retweet_count { get; set; }
        public int favorite_count { get; set; }
        public long user_id { get; set; }
        public string text { get; set; }
        public long source_id { get; set; }
    
        public virtual source source { get; set; }
    }
}
